### ISSUE TITLE
a question for cuda env

### ISSUE THREAD

**Issue by jqu314159** [salesforce/warp-drive#43]
There is reset in the python environment, but in cuda they do not, suppose I want each environment agent to be able to set a different initial position, how can I write it in cuda?

**Comment by Emerald01** [comment]
We have CUDA reset function that pushes the data from CPU host to the GPU in the very beginning and later used this original host start point to reset directly inside the GPU, the Python API is here
https://github.com/salesforce/warp-drive/blob/4f380f839bad003010ef98868ad143899c8c46d0/warp_drive/managers/function_manager.py#L787
And the backend CUDA code is here
https://github.com/salesforce/warp-drive/blob/master/warp_drive/cuda_includes/core/reset.h

The current problem is this: we used the original random state generated by the Python API but as you know, it is a single env instance. So we expand at the environment dimension to use this initial state for all the environment replicas managed by GPU blocks. This will make Python simulation and GPU simulation seamlessly the same with all APIs, and we will not have repeated data transfer btw CPU/GPU
https://github.com/salesforce/warp-drive/blob/4f380f839bad003010ef98868ad143899c8c46d0/warp_drive/env_wrapper.py#L213

Although the randomness and coverage of the states is guaranteed due to random sampling process in step function, it is ideal that each environment replica could have a different random state or a set of random states to start with. It may not be critical for Tag game, but for some environments, different starting configuration could have different meanings. There are two options in my mind:
1. implement a GPU randomness reset function, however, this would be env by env which is somehow against the generic rule for the utility functions of WarpDrive
2. provide a set of random initial states, and at each reset, every environment replica can pick up one, so one extreme case would be all environments share the same initial state as we do now, and another extreme is each environment replica has its own
The second choice seems a better choice, and not hard to do. The reason we have not yet implemented it is because this means we will provide a initial states pool somewhere in the EnvWrapper, which makes API a little ugly.

Please let me know your thoughts, if you want, we can proceed with option 2 or some better ideas.

**Comment by jqu314159** [comment]
Sorry for the late response, my idea is that the cuda you provide is __global__ CudaSteps, but I hope that each iteration can provide a random value, so that I can change the state or relative relationship of the agent in each iteration(This operation can without each iteration, the purpose is to provide more diversity for environment learning), I hope in There is a __device__ func that can be used in cuda __global__ during training just like the reward function, I believe it should be better uderstand than adding in EnvWrapper, but it depends on how you design it, Thanks to the 
warp-drive team for helping me learn MUTI RL

**Comment by jqu314159** [comment]
In order to make the environment more complex, you can also design a parameter in WarpDrive. At the beginning, you can set several enviroments to be used. During training, you can use random to generate several enviroments first, and choose them randomly at different iterations.
