### ISSUE TITLE
'EnvWrapper' object has no attribute 'use_cuda' 

### ISSUE THREAD

**Issue by Mshz2** [salesforce/warp-drive#56]
Hi, thanks for you great contribution with warp_drive. I am just following the tutorial of [tutorial-7-training_with_warp_drive_and_pytorch_lightning](https://github.com/salesforce/warp-drive/blob/master/tutorials/tutorial-7-training_with_warp_drive_and_pytorch_lightning.ipynb). I have no error until the cell which we use EnvWrapper:
![image](https://user-images.githubusercontent.com/63469924/197833973-7c3e94f3-db23-4bfe-8d6f-88cd3356e91b.png)

I just installed the exact packages in the tutorial but still get the error of `AttributeError: 'EnvWrapper' object has no attribute 'use_cuda'
`. Thanks for your support.

**Comment by Emerald01** [comment]
Hi @Mshz2 
Thank you for trying our code. We recently have a big update for the codebase (and it bumps up to version 2.0). It now has dual support for both CUDA C and Numba, therefore instead of `env_wrapper.use_cuda = True or False`, it changes to `env_wrapper.env_backend = "pycuda", "numba" or "cpu"`. I believe all other tutorials have been modified accordingly and env_wrapper itself has internal backward compatibility too, but we have not yet update the lightning one. We will update it shortly, thank you for your patience.

**Comment by Emerald01** [comment]
Fixed, the latest version 2.1 includes the fix. @Mshz2

**Comment by Mshz2** [comment]
> Fixed, the latest version 2.1 includes the fix. @Mshz2

Many thanks for your support.
